### ISSUE TITLE
The runtime parameter of nodejs8.10 is no longer supported

### ISSUE THREAD

**Issue by mmeloni** [riboseinc/terraform-aws-lambda-edge-authentication#12]
Hi it's seems that you need to update the nodejs runtime environment.

>  The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions.

**Comment by igormq** [comment]
Resolved in #13

**Comment by ronaldtse** [comment]
#13 is merged, closing. Thanks @igormq !
