### ISSUE TITLE
Add authentication outcome of "allowing a browser to access a private S3 website"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/terraform-aws-lambda-edge-authentication#4]
Right now the authentication outcome is purely to provide access to a file.

In some cases, an S3 website (https://github.com/riboseinc/terraform-aws-s3-cloudfront-website) needs to provide private access to certain IP addresses only.

This means that:
1. User will first authenticate with lambda edge function using AWS credentials, this will add the user's IP address to some place for 15 minutes (or "X" minutes)
2. Within these 15 minutes, the user can access this Cloudfront origin (backed with S3 website).
3. After 15 minutes, the user's IP will be removed and the user cannot access any data on this S3 website.

**Comment by ronaldtse** [comment]
Instead of:

```js
const authUser = '${BASIC_USER}';
const authPass = '${BASIC_PWD}';
```

We will want to use AWS user accounts to authenticate.

For example, under the S3 website setup (https://github.com/riboseinc/terraform-aws-s3-cloudfront-website), we can:

1. Setup a Cloudfront Lambda Edge function that creates Signed Cookies on the user's browser.
2. When user access this Lambda Edge function, it will create a Signed Cookie for the user and adds to the user's browser.
3. Then the browser can use this Signed Cookie for X minutes without authenticating.
4. The server side does not need persistence (or IP address).
5. Only when the cookie expires the user needs to access to this Lambda endpoint again

**Comment by ronaldtse** [comment]
Actually, we just need to update this Lambda JS function (in this repo) to set the cookie like this:
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html

```js
    const request = event.Records[0].cf.request;
    const headers = request.headers;
    const authCookie = 'My-Special-Auth-Cookie=AFHJAkfhasfhlafskaj';

    let experimentUri;
    if (headers.cookie) {
        for (let i = 0; i < headers.cookie.length; i++) {
            if (headers.cookie[i].value.indexOf(authCookie) >= 0) {
                console.log('authCookie found');
                if (valid) {
                    // allow access
                    // set new authCookie to persist session
                } else {
                    // return 403;
                }
                break;
            }
        }
    }
```

**Comment by ronaldtse** [comment]
References:

* https://aws.amazon.com/blogs/networking-and-content-delivery/serving-private-content-using-amazon-cloudfront-aws-lambdaedge/

* https://github.com/thumbsup/lambda-cloudfront-cookies (KMS)

* https://github.com/freakingawesome/lambda-cloudfront-cookies/commit/fe204b4f364ab8feba3565917956d3fd678b78a2 (No KMS needed)

**Comment by phuonghuynh** [comment]
@ronaldtse CloudFront signed cookie protect the whole Distribution which is not the purpose of this module. Check the document [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html#private-content-adding-trusted-signers)

**Comment by ronaldtse** [comment]
@phuonghuynh you're right, we should use Lambda@Edge implementation, and should not use the CloudFront Signed Cookies. We could however generate/authenticate using signed cookies ourselves in the Lambda implementation.
 
For example, we have a static website that has parts that need protection. But we want session-based because we don't want a person to authenticate multiple times.
 
So they should go to a "login" URL, authenticate once with username/password, and then they will have a cookie to access the private parts of the website for a certain time.

**Comment by ronaldtse** [comment]
I think this is all done and implemented. @phuonghuynh please re-open if it's not. Thanks!
